# Generated by Django 3.1.7 on 2021-04-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('to_do', '0002_auto_20210420_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('text', models.CharField(max_length=200, verbose_name='Reminder Text')),
                ('reminder_date', models.DateTimeField(verbose_name='Reminder Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do.todoitem', verbose_name='ToDo')),
            ],
        ),
    ]
